name: CI/CD with Terraform
on:
push:
branches:
- complete-CI/CD-with_Terraform-AWS
env:
AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
AWS_SECRET_ACESS_KEY_ID: ${{ secrets.AWS_SECRET_ACCESS_KEY_ID }}
TF_STATE_BUCKET_NAME: ${{ secrets.AWS_STATE_BUCKET_NAME }}
PRIVATE_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PRIVATE }}
PUBLIC_SSH_KEY: ${{ secrets.AWS_SSH_KEY_PUBLIC }}
AWS_REGION: us-east-1
jobs: 
  deploy-infra:
    runs-on: ubuntu-latest
    steps:
    - name: Cheackout
      uses: actions/checkout@v2
    - name: setup Terraform
      uses: hashicorp/setup-terraform@v1
      with: 
        terraform_wrapper: false
    - name: Terraform init
      id: init 
      run: terraform init -backend-config="bucket=$AWS_STATE_BUCKET_NAME" -backend-config="region=us-east-1"   
      working-directory: ./terraform 
    - name: Terraform plan
      id: plan
      run: |
        terraform plan \
        -var="region=us-east-1" \
        -var="public_key=$PUBLIC_SSH_KEY" \
        -var="private_key=$PRIVATE_SSH_KEY" \
        -var="key_name=deployer-key"
        -out=plan
      working-directory: ./terraform 
    - name: Terraform Apply
      id: apply
      run: terraform apply plan -auto-approve plan
      working-directory: ./terraform

